version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m pip install --upgrade setuptools wheel && python3 setup.py sdist bdist_wheel
          name: Build
      - run:
          command: pip install dist/portformer-1.0.0-py3-none-any.whl
          name: Install
      - run:
          command: python ./tests/all.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
